sudo: required
language: scala
scala:
  - 2.12.3
jdk:
  - oraclejdk8

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

script:
- sbt ++$TRAVIS_SCALA_VERSION test
# Tricks to avoid unnecessary cache updates, from
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  yarn: true
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.sbt/0.13/dependency
    - $HOME/.cache/yarn
    - $HOME/.cache/npm
